name: artspeak_flutter
description: ArtSpeak - AI Art Therapy System for Autistic Individuals (frontend prototype)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  camera: ^0.10.5+9
  path_provider: ^2.1.1
  fl_chart: ^0.66.2
  intl: ^0.19.0
  video_player: ^2.8.2
  supabase_flutter: ^2.10.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
